Aviva_FizzBuzz_Tapas_TDD/Models/CommandInvoker.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Aviva_FizzBuzz_Tapas_TDD.BL.Contacts;

namespace Aviva_FizzBuzz_Tapas_TDD.Models
{
    public class CommandInvoker
    {
        public void Invoke(IFizzBuzzBL cmdObj)
        {
            cmdObj.GetFizzBuzzNumbers();
        }
    }
}

Aviva_FizzBuzz_Tapas_TDD/Controllers/FizzBuzzController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Aviva_FizzBuzz_Tapas_TDD.ViewModel;
using Aviva_FizzBuzz_Tapas_TDD.BL;
using Aviva_FizzBuzz_Tapas_TDD.Contract;

namespace Aviva_FizzBuzz_Tapas_TDD.Controllers
{
    public class FizzBuzzController : Controller
    {
        public IFizzBuzzViewModel FizzBuzzModel { get; set; }
       
        public FizzBuzzController(IFizzBuzzViewModel fizzBuzzModel)
        {
            FizzBuzzModel = fizzBuzzModel;
        }

        public ActionResult Show()
        {
            return View("Show");
        }
        public ActionResult Submit(string maxNumber)
         {
            if (ModelState.IsValid)
            {
                FizzBuzzModel.MaxNumber = Int32.Parse(maxNumber);
                FizzBuzzModel.GetFizzBuzzNumbers();
                return View("Show", FizzBuzzModel);
            }
            else
            {
                return View("Show", FizzBuzzModel);
            }
        }
    }
}

Aviva_FizzBuzz_Tapas_TDD/Views/FizzBuzz/Display.cshtml
@model Aviva_FizzBuzz_Tapas_TDD.ViewModel.FizzBuzzViewModel
<script src="~/Scripts/jquery-2.2.0.min.js"></script>
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<link href="~/StyleSheets/jquery.dataTables.min.css" rel="stylesheet" />
<table id="displayFizzBuzzNumber" >
    <thead>
        <tr>
            <th>FizzBuzz Numbers</th>           
        </tr>
    </thead>
    <tbody>
@foreach (var fizzBuzzNumber in @Model.FizzBuzzNumbers)
{
    <tr>
        <td><span>@fizzBuzzNumber.DisplayText</span> </td>
    </tr>
}
    </tbody>
</table>

<script type="text/javascript">
    $(document).ready(function () {
            $('#displayFizzBuzzNumber').DataTable({
            createdRow: function (row) {
                $('td', row);
            },
            ordering: false,
            searching: false,
            pagingType: "simple",
            type: "POST",
            bLengthChange: false,
            iDisplayLength: 20
        });
    });
    
   
</script>

Aviva_FizzBuzz_Tapas_TDD/Views/FizzBuzz/Show.cshtml
@model Aviva_FizzBuzz_Tapas_TDD.ViewModel.FizzBuzzViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Show</title>
</head>
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<body>
    <div> 
        @using (Html.BeginForm("Submit", "FizzBuzz", FormMethod.Post))
        {
            <i>Enter Maximum Number:</i>@Html.TextBoxFor(m => m.MaxNumber)
            <input id="Submit1" type="submit" value="Click Here" /><br />
            @Html.ValidationMessageFor(x => x.MaxNumber)
            <br />

            if (Model != null)
            {
                @Html.Partial("Display", Model)
            }
        }
    </div>
</body>
</html>